# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OhMyLove' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OhMyLove

  target 'OhMyLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OhMyLoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry'
pod 'YYModel'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'GTMBase64'
pod 'UMessage'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'MBProgressHUD'

end
